import type { Metadata } from 'next';
import { Inter, DotGothic16 } from 'next/font/google';
import './globals.css';
import { ChakraProvider } from '@chakra-ui/react';
import AppBgImg from './AppBgImg';
import AuthProvider from '../../context/AuthProvider';

const inter = Inter({ subsets: ['latin'], variable: '--font-inter' });

export const dotGothic16 = DotGothic16({
  weight: '400',
  subsets: ['latin'],
  variable: '--font-dotgothic16',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${inter.variable} ${dotGothic16.variable}`}>
      <body>
        <AuthProvider>
          <ChakraProvider>
            <AppBgImg />

            {children}
          </ChakraProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
